// Code generated from the ISO 4217 list shipped with moneyphp/money (resources/currency.php). DO NOT EDIT.

package money

// isoCurrencies holds every active ISO 4217 currency keyed by its alphabetic code.
var isoCurrencies = map[string]Currency{
	"AED": {code: "AED", name: "UAE Dirham", minorUnits: 2, numericCode: 784},
	"AFN": {code: "AFN", name: "Afghani", minorUnits: 2, numericCode: 971},
	"ALL": {code: "ALL", name: "Lek", minorUnits: 2, numericCode: 8},
	"AMD": {code: "AMD", name: "Armenian Dram", minorUnits: 2, numericCode: 51},
	"AOA": {code: "AOA", name: "Kwanza", minorUnits: 2, numericCode: 973},
	"ARS": {code: "ARS", name: "Argentine Peso", minorUnits: 2, numericCode: 32},
	"AUD": {code: "AUD", name: "Australian Dollar", minorUnits: 2, numericCode: 36},
	"AWG": {code: "AWG", name: "Aruban Florin", minorUnits: 2, numericCode: 533},
	"AZN": {code: "AZN", name: "Azerbaijan Manat", minorUnits: 2, numericCode: 944},
	"BAM": {code: "BAM", name: "Convertible Mark", minorUnits: 2, numericCode: 977},
	"BBD": {code: "BBD", name: "Barbados Dollar", minorUnits: 2, numericCode: 52},
	"BDT": {code: "BDT", name: "Taka", minorUnits: 2, numericCode: 50},
	"BGN": {code: "BGN", name: "Bulgarian Lev", minorUnits: 2, numericCode: 975},
	"BHD": {code: "BHD", name: "Bahraini Dinar", minorUnits: 3, numericCode: 48},
	"BIF": {code: "BIF", name: "Burundi Franc", minorUnits: 0, numericCode: 108},
	"BMD": {code: "BMD", name: "Bermudian Dollar", minorUnits: 2, numericCode: 60},
	"BND": {code: "BND", name: "Brunei Dollar", minorUnits: 2, numericCode: 96},
	"BOB": {code: "BOB", name: "Boliviano", minorUnits: 2, numericCode: 68},
	"BOV": {code: "BOV", name: "Mvdol", minorUnits: 2, numericCode: 984},
	"BRL": {code: "BRL", name: "Brazilian Real", minorUnits: 2, numericCode: 986},
	"BSD": {code: "BSD", name: "Bahamian Dollar", minorUnits: 2, numericCode: 44},
	"BTN": {code: "BTN", name: "Ngultrum", minorUnits: 2, numericCode: 64},
	"BWP": {code: "BWP", name: "Pula", minorUnits: 2, numericCode: 72},
	"BYN": {code: "BYN", name: "Belarusian Ruble", minorUnits: 2, numericCode: 933},
	"BZD": {code: "BZD", name: "Belize Dollar", minorUnits: 2, numericCode: 84},
	"CAD": {code: "CAD", name: "Canadian Dollar", minorUnits: 2, numericCode: 124},
	"CDF": {code: "CDF", name: "Congolese Franc", minorUnits: 2, numericCode: 976},
	"CHE": {code: "CHE", name: "WIR Euro", minorUnits: 2, numericCode: 947},
	"CHF": {code: "CHF", name: "Swiss Franc", minorUnits: 2, numericCode: 756},
	"CHW": {code: "CHW", name: "WIR Franc", minorUnits: 2, numericCode: 948},
	"CLF": {code: "CLF", name: "Unidad de Fomento", minorUnits: 4, numericCode: 990},
	"CLP": {code: "CLP", name: "Chilean Peso", minorUnits: 0, numericCode: 152},
	"CNY": {code: "CNY", name: "Yuan Renminbi", minorUnits: 2, numericCode: 156},
	"COP": {code: "COP", name: "Colombian Peso", minorUnits: 2, numericCode: 170},
	"COU": {code: "COU", name: "Unidad de Valor Real", minorUnits: 2, numericCode: 970},
	"CRC": {code: "CRC", name: "Costa Rican Colon", minorUnits: 2, numericCode: 188},
	"CUP": {code: "CUP", name: "Cuban Peso", minorUnits: 2, numericCode: 192},
	"CVE": {code: "CVE", name: "Cabo Verde Escudo", minorUnits: 2, numericCode: 132},
	"CZK": {code: "CZK", name: "Czech Koruna", minorUnits: 2, numericCode: 203},
	"DJF": {code: "DJF", name: "Djibouti Franc", minorUnits: 0, numericCode: 262},
	"DKK": {code: "DKK", name: "Danish Krone", minorUnits: 2, numericCode: 208},
	"DOP": {code: "DOP", name: "Dominican Peso", minorUnits: 2, numericCode: 214},
	"DZD": {code: "DZD", name: "Algerian Dinar", minorUnits: 2, numericCode: 12},
	"EGP": {code: "EGP", name: "Egyptian Pound", minorUnits: 2, numericCode: 818},
	"ERN": {code: "ERN", name: "Nakfa", minorUnits: 2, numericCode: 232},
	"ETB": {code: "ETB", name: "Ethiopian Birr", minorUnits: 2, numericCode: 230},
	"EUR": {code: "EUR", name: "Euro", minorUnits: 2, numericCode: 978},
	"FJD": {code: "FJD", name: "Fiji Dollar", minorUnits: 2, numericCode: 242},
	"FKP": {code: "FKP", name: "Falkland Islands Pound", minorUnits: 2, numericCode: 238},
	"GBP": {code: "GBP", name: "Pound Sterling", minorUnits: 2, numericCode: 826},
	"GEL": {code: "GEL", name: "Lari", minorUnits: 2, numericCode: 981},
	"GHS": {code: "GHS", name: "Ghana Cedi", minorUnits: 2, numericCode: 936},
	"GIP": {code: "GIP", name: "Gibraltar Pound", minorUnits: 2, numericCode: 292},
	"GMD": {code: "GMD", name: "Dalasi", minorUnits: 2, numericCode: 270},
	"GNF": {code: "GNF", name: "Guinean Franc", minorUnits: 0, numericCode: 324},
	"GTQ": {code: "GTQ", name: "Quetzal", minorUnits: 2, numericCode: 320},
	"GYD": {code: "GYD", name: "Guyana Dollar", minorUnits: 2, numericCode: 328},
	"HKD": {code: "HKD", name: "Hong Kong Dollar", minorUnits: 2, numericCode: 344},
	"HNL": {code: "HNL", name: "Lempira", minorUnits: 2, numericCode: 340},
	"HTG": {code: "HTG", name: "Gourde", minorUnits: 2, numericCode: 332},
	"HUF": {code: "HUF", name: "Forint", minorUnits: 2, numericCode: 348},
	"IDR": {code: "IDR", name: "Rupiah", minorUnits: 2, numericCode: 360},
	"ILS": {code: "ILS", name: "New Israeli Sheqel", minorUnits: 2, numericCode: 376},
	"INR": {code: "INR", name: "Indian Rupee", minorUnits: 2, numericCode: 356},
	"IQD": {code: "IQD", name: "Iraqi Dinar", minorUnits: 3, numericCode: 368},
	"IRR": {code: "IRR", name: "Iranian Rial", minorUnits: 2, numericCode: 364},
	"ISK": {code: "ISK", name: "Iceland Krona", minorUnits: 0, numericCode: 352},
	"JMD": {code: "JMD", name: "Jamaican Dollar", minorUnits: 2, numericCode: 388},
	"JOD": {code: "JOD", name: "Jordanian Dinar", minorUnits: 3, numericCode: 400},
	"JPY": {code: "JPY", name: "Yen", minorUnits: 0, numericCode: 392},
	"KES": {code: "KES", name: "Kenyan Shilling", minorUnits: 2, numericCode: 404},
	"KGS": {code: "KGS", name: "Som", minorUnits: 2, numericCode: 417},
	"KHR": {code: "KHR", name: "Riel", minorUnits: 2, numericCode: 116},
	"KMF": {code: "KMF", name: "Comorian Franc ", minorUnits: 0, numericCode: 174},
	"KPW": {code: "KPW", name: "North Korean Won", minorUnits: 2, numericCode: 408},
	"KRW": {code: "KRW", name: "Won", minorUnits: 0, numericCode: 410},
	"KWD": {code: "KWD", name: "Kuwaiti Dinar", minorUnits: 3, numericCode: 414},
	"KYD": {code: "KYD", name: "Cayman Islands Dollar", minorUnits: 2, numericCode: 136},
	"KZT": {code: "KZT", name: "Tenge", minorUnits: 2, numericCode: 398},
	"LAK": {code: "LAK", name: "Lao Kip", minorUnits: 2, numericCode: 418},
	"LBP": {code: "LBP", name: "Lebanese Pound", minorUnits: 2, numericCode: 422},
	"LKR": {code: "LKR", name: "Sri Lanka Rupee", minorUnits: 2, numericCode: 144},
	"LRD": {code: "LRD", name: "Liberian Dollar", minorUnits: 2, numericCode: 430},
	"LSL": {code: "LSL", name: "Loti", minorUnits: 2, numericCode: 426},
	"LYD": {code: "LYD", name: "Libyan Dinar", minorUnits: 3, numericCode: 434},
	"MAD": {code: "MAD", name: "Moroccan Dirham", minorUnits: 2, numericCode: 504},
	"MDL": {code: "MDL", name: "Moldovan Leu", minorUnits: 2, numericCode: 498},
	"MGA": {code: "MGA", name: "Malagasy Ariary", minorUnits: 2, numericCode: 969},
	"MKD": {code: "MKD", name: "Denar", minorUnits: 2, numericCode: 807},
	"MMK": {code: "MMK", name: "Kyat", minorUnits: 2, numericCode: 104},
	"MNT": {code: "MNT", name: "Tugrik", minorUnits: 2, numericCode: 496},
	"MOP": {code: "MOP", name: "Pataca", minorUnits: 2, numericCode: 446},
	"MRU": {code: "MRU", name: "Ouguiya", minorUnits: 2, numericCode: 929},
	"MUR": {code: "MUR", name: "Mauritius Rupee", minorUnits: 2, numericCode: 480},
	"MVR": {code: "MVR", name: "Rufiyaa", minorUnits: 2, numericCode: 462},
	"MWK": {code: "MWK", name: "Malawi Kwacha", minorUnits: 2, numericCode: 454},
	"MXN": {code: "MXN", name: "Mexican Peso", minorUnits: 2, numericCode: 484},
	"MXV": {code: "MXV", name: "Mexican Unidad de Inversion (UDI)", minorUnits: 2, numericCode: 979},
	"MYR": {code: "MYR", name: "Malaysian Ringgit", minorUnits: 2, numericCode: 458},
	"MZN": {code: "MZN", name: "Mozambique Metical", minorUnits: 2, numericCode: 943},
	"NAD": {code: "NAD", name: "Namibia Dollar", minorUnits: 2, numericCode: 516},
	"NGN": {code: "NGN", name: "Naira", minorUnits: 2, numericCode: 566},
	"NIO": {code: "NIO", name: "Cordoba Oro", minorUnits: 2, numericCode: 558},
	"NOK": {code: "NOK", name: "Norwegian Krone", minorUnits: 2, numericCode: 578},
	"NPR": {code: "NPR", name: "Nepalese Rupee", minorUnits: 2, numericCode: 524},
	"NZD": {code: "NZD", name: "New Zealand Dollar", minorUnits: 2, numericCode: 554},
	"OMR": {code: "OMR", name: "Rial Omani", minorUnits: 3, numericCode: 512},
	"PAB": {code: "PAB", name: "Balboa", minorUnits: 2, numericCode: 590},
	"PEN": {code: "PEN", name: "Sol", minorUnits: 2, numericCode: 604},
	"PGK": {code: "PGK", name: "Kina", minorUnits: 2, numericCode: 598},
	"PHP": {code: "PHP", name: "Philippine Peso", minorUnits: 2, numericCode: 608},
	"PKR": {code: "PKR", name: "Pakistan Rupee", minorUnits: 2, numericCode: 586},
	"PLN": {code: "PLN", name: "Zloty", minorUnits: 2, numericCode: 985},
	"PYG": {code: "PYG", name: "Guarani", minorUnits: 0, numericCode: 600},
	"QAR": {code: "QAR", name: "Qatari Rial", minorUnits: 2, numericCode: 634},
	"RON": {code: "RON", name: "Romanian Leu", minorUnits: 2, numericCode: 946},
	"RSD": {code: "RSD", name: "Serbian Dinar", minorUnits: 2, numericCode: 941},
	"RUB": {code: "RUB", name: "Russian Ruble", minorUnits: 2, numericCode: 643},
	"RWF": {code: "RWF", name: "Rwanda Franc", minorUnits: 0, numericCode: 646},
	"SAR": {code: "SAR", name: "Saudi Riyal", minorUnits: 2, numericCode: 682},
	"SBD": {code: "SBD", name: "Solomon Islands Dollar", minorUnits: 2, numericCode: 90},
	"SCR": {code: "SCR", name: "Seychelles Rupee", minorUnits: 2, numericCode: 690},
	"SDG": {code: "SDG", name: "Sudanese Pound", minorUnits: 2, numericCode: 938},
	"SEK": {code: "SEK", name: "Swedish Krona", minorUnits: 2, numericCode: 752},
	"SGD": {code: "SGD", name: "Singapore Dollar", minorUnits: 2, numericCode: 702},
	"SHP": {code: "SHP", name: "Saint Helena Pound", minorUnits: 2, numericCode: 654},
	"SLE": {code: "SLE", name: "Leone", minorUnits: 2, numericCode: 925},
	"SOS": {code: "SOS", name: "Somali Shilling", minorUnits: 2, numericCode: 706},
	"SRD": {code: "SRD", name: "Surinam Dollar", minorUnits: 2, numericCode: 968},
	"SSP": {code: "SSP", name: "South Sudanese Pound", minorUnits: 2, numericCode: 728},
	"STN": {code: "STN", name: "Dobra", minorUnits: 2, numericCode: 930},
	"SVC": {code: "SVC", name: "El Salvador Colon", minorUnits: 2, numericCode: 222},
	"SYP": {code: "SYP", name: "Syrian Pound", minorUnits: 2, numericCode: 760},
	"SZL": {code: "SZL", name: "Lilangeni", minorUnits: 2, numericCode: 748},
	"THB": {code: "THB", name: "Baht", minorUnits: 2, numericCode: 764},
	"TJS": {code: "TJS", name: "Somoni", minorUnits: 2, numericCode: 972},
	"TMT": {code: "TMT", name: "Turkmenistan New Manat", minorUnits: 2, numericCode: 934},
	"TND": {code: "TND", name: "Tunisian Dinar", minorUnits: 3, numericCode: 788},
	"TOP": {code: "TOP", name: "Pa’anga", minorUnits: 2, numericCode: 776},
	"TRY": {code: "TRY", name: "Turkish Lira", minorUnits: 2, numericCode: 949},
	"TTD": {code: "TTD", name: "Trinidad and Tobago Dollar", minorUnits: 2, numericCode: 780},
	"TWD": {code: "TWD", name: "New Taiwan Dollar", minorUnits: 2, numericCode: 901},
	"TZS": {code: "TZS", name: "Tanzanian Shilling", minorUnits: 2, numericCode: 834},
	"UAH": {code: "UAH", name: "Hryvnia", minorUnits: 2, numericCode: 980},
	"UGX": {code: "UGX", name: "Uganda Shilling", minorUnits: 0, numericCode: 800},
	"USD": {code: "USD", name: "US Dollar", minorUnits: 2, numericCode: 840},
	"USN": {code: "USN", name: "US Dollar (Next day)", minorUnits: 2, numericCode: 997},
	"UYI": {code: "UYI", name: "Uruguay Peso en Unidades Indexadas (UI)", minorUnits: 0, numericCode: 940},
	"UYU": {code: "UYU", name: "Peso Uruguayo", minorUnits: 2, numericCode: 858},
	"UYW": {code: "UYW", name: "Unidad Previsional", minorUnits: 4, numericCode: 927},
	"UZS": {code: "UZS", name: "Uzbekistan Sum", minorUnits: 2, numericCode: 860},
	"VED": {code: "VED", name: "Bolívar Soberano", minorUnits: 2, numericCode: 926},
	"VES": {code: "VES", name: "Bolívar Soberano", minorUnits: 2, numericCode: 928},
	"VND": {code: "VND", name: "Dong", minorUnits: 0, numericCode: 704},
	"VUV": {code: "VUV", name: "Vatu", minorUnits: 0, numericCode: 548},
	"WST": {code: "WST", name: "Tala", minorUnits: 2, numericCode: 882},
	"XAD": {code: "XAD", name: "Arab Accounting Dinar", minorUnits: 2, numericCode: 396},
	"XAF": {code: "XAF", name: "CFA Franc BEAC", minorUnits: 0, numericCode: 950},
	"XAG": {code: "XAG", name: "Silver", minorUnits: 0, numericCode: 961},
	"XAU": {code: "XAU", name: "Gold", minorUnits: 0, numericCode: 959},
	"XBA": {code: "XBA", name: "Bond Markets Unit European Composite Unit (EURCO)", minorUnits: 0, numericCode: 955},
	"XBB": {code: "XBB", name: "Bond Markets Unit European Monetary Unit (E.M.U.-6)", minorUnits: 0, numericCode: 956},
	"XBC": {code: "XBC", name: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)", minorUnits: 0, numericCode: 957},
	"XBD": {code: "XBD", name: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)", minorUnits: 0, numericCode: 958},
	"XCD": {code: "XCD", name: "East Caribbean Dollar", minorUnits: 2, numericCode: 951},
	"XCG": {code: "XCG", name: "Caribbean Guilder", minorUnits: 2, numericCode: 532},
	"XDR": {code: "XDR", name: "SDR (Special Drawing Right)", minorUnits: 0, numericCode: 960},
	"XOF": {code: "XOF", name: "CFA Franc BCEAO", minorUnits: 0, numericCode: 952},
	"XPD": {code: "XPD", name: "Palladium", minorUnits: 0, numericCode: 964},
	"XPF": {code: "XPF", name: "CFP Franc", minorUnits: 0, numericCode: 953},
	"XPT": {code: "XPT", name: "Platinum", minorUnits: 0, numericCode: 962},
	"XSU": {code: "XSU", name: "Sucre", minorUnits: 0, numericCode: 994},
	"XTS": {code: "XTS", name: "Codes specifically reserved for testing purposes", minorUnits: 0, numericCode: 963},
	"XUA": {code: "XUA", name: "ADB Unit of Account", minorUnits: 0, numericCode: 965},
	"XXX": {code: "XXX", name: "The codes assigned for transactions where no currency is involved", minorUnits: 0, numericCode: 999},
	"YER": {code: "YER", name: "Yemeni Rial", minorUnits: 2, numericCode: 886},
	"ZAR": {code: "ZAR", name: "Rand", minorUnits: 2, numericCode: 710},
	"ZMW": {code: "ZMW", name: "Zambian Kwacha", minorUnits: 2, numericCode: 967},
	"ZWG": {code: "ZWG", name: "Zimbabwe Gold", minorUnits: 2, numericCode: 924},
}
