// Code generated from the ISO 4217 list shipped with moneyphp/money (resources/currency.php). DO NOT EDIT.

package iso_test

import (
	"testing"

	money "github.com/laranex/goravel-money/v4"
	"github.com/laranex/goravel-money/v4/iso"
)

// TestEveryMarkerIsAnISOCurrency checks that each marker resolves to the currency it names.
func TestEveryMarkerIsAnISOCurrency(t *testing.T) {
	markers := map[string]money.CurrencyCode{
		"AED": iso.AED{},
		"AFN": iso.AFN{},
		"ALL": iso.ALL{},
		"AMD": iso.AMD{},
		"AOA": iso.AOA{},
		"ARS": iso.ARS{},
		"AUD": iso.AUD{},
		"AWG": iso.AWG{},
		"AZN": iso.AZN{},
		"BAM": iso.BAM{},
		"BBD": iso.BBD{},
		"BDT": iso.BDT{},
		"BGN": iso.BGN{},
		"BHD": iso.BHD{},
		"BIF": iso.BIF{},
		"BMD": iso.BMD{},
		"BND": iso.BND{},
		"BOB": iso.BOB{},
		"BOV": iso.BOV{},
		"BRL": iso.BRL{},
		"BSD": iso.BSD{},
		"BTN": iso.BTN{},
		"BWP": iso.BWP{},
		"BYN": iso.BYN{},
		"BZD": iso.BZD{},
		"CAD": iso.CAD{},
		"CDF": iso.CDF{},
		"CHE": iso.CHE{},
		"CHF": iso.CHF{},
		"CHW": iso.CHW{},
		"CLF": iso.CLF{},
		"CLP": iso.CLP{},
		"CNY": iso.CNY{},
		"COP": iso.COP{},
		"COU": iso.COU{},
		"CRC": iso.CRC{},
		"CUP": iso.CUP{},
		"CVE": iso.CVE{},
		"CZK": iso.CZK{},
		"DJF": iso.DJF{},
		"DKK": iso.DKK{},
		"DOP": iso.DOP{},
		"DZD": iso.DZD{},
		"EGP": iso.EGP{},
		"ERN": iso.ERN{},
		"ETB": iso.ETB{},
		"EUR": iso.EUR{},
		"FJD": iso.FJD{},
		"FKP": iso.FKP{},
		"GBP": iso.GBP{},
		"GEL": iso.GEL{},
		"GHS": iso.GHS{},
		"GIP": iso.GIP{},
		"GMD": iso.GMD{},
		"GNF": iso.GNF{},
		"GTQ": iso.GTQ{},
		"GYD": iso.GYD{},
		"HKD": iso.HKD{},
		"HNL": iso.HNL{},
		"HTG": iso.HTG{},
		"HUF": iso.HUF{},
		"IDR": iso.IDR{},
		"ILS": iso.ILS{},
		"INR": iso.INR{},
		"IQD": iso.IQD{},
		"IRR": iso.IRR{},
		"ISK": iso.ISK{},
		"JMD": iso.JMD{},
		"JOD": iso.JOD{},
		"JPY": iso.JPY{},
		"KES": iso.KES{},
		"KGS": iso.KGS{},
		"KHR": iso.KHR{},
		"KMF": iso.KMF{},
		"KPW": iso.KPW{},
		"KRW": iso.KRW{},
		"KWD": iso.KWD{},
		"KYD": iso.KYD{},
		"KZT": iso.KZT{},
		"LAK": iso.LAK{},
		"LBP": iso.LBP{},
		"LKR": iso.LKR{},
		"LRD": iso.LRD{},
		"LSL": iso.LSL{},
		"LYD": iso.LYD{},
		"MAD": iso.MAD{},
		"MDL": iso.MDL{},
		"MGA": iso.MGA{},
		"MKD": iso.MKD{},
		"MMK": iso.MMK{},
		"MNT": iso.MNT{},
		"MOP": iso.MOP{},
		"MRU": iso.MRU{},
		"MUR": iso.MUR{},
		"MVR": iso.MVR{},
		"MWK": iso.MWK{},
		"MXN": iso.MXN{},
		"MXV": iso.MXV{},
		"MYR": iso.MYR{},
		"MZN": iso.MZN{},
		"NAD": iso.NAD{},
		"NGN": iso.NGN{},
		"NIO": iso.NIO{},
		"NOK": iso.NOK{},
		"NPR": iso.NPR{},
		"NZD": iso.NZD{},
		"OMR": iso.OMR{},
		"PAB": iso.PAB{},
		"PEN": iso.PEN{},
		"PGK": iso.PGK{},
		"PHP": iso.PHP{},
		"PKR": iso.PKR{},
		"PLN": iso.PLN{},
		"PYG": iso.PYG{},
		"QAR": iso.QAR{},
		"RON": iso.RON{},
		"RSD": iso.RSD{},
		"RUB": iso.RUB{},
		"RWF": iso.RWF{},
		"SAR": iso.SAR{},
		"SBD": iso.SBD{},
		"SCR": iso.SCR{},
		"SDG": iso.SDG{},
		"SEK": iso.SEK{},
		"SGD": iso.SGD{},
		"SHP": iso.SHP{},
		"SLE": iso.SLE{},
		"SOS": iso.SOS{},
		"SRD": iso.SRD{},
		"SSP": iso.SSP{},
		"STN": iso.STN{},
		"SVC": iso.SVC{},
		"SYP": iso.SYP{},
		"SZL": iso.SZL{},
		"THB": iso.THB{},
		"TJS": iso.TJS{},
		"TMT": iso.TMT{},
		"TND": iso.TND{},
		"TOP": iso.TOP{},
		"TRY": iso.TRY{},
		"TTD": iso.TTD{},
		"TWD": iso.TWD{},
		"TZS": iso.TZS{},
		"UAH": iso.UAH{},
		"UGX": iso.UGX{},
		"USD": iso.USD{},
		"USN": iso.USN{},
		"UYI": iso.UYI{},
		"UYU": iso.UYU{},
		"UYW": iso.UYW{},
		"UZS": iso.UZS{},
		"VED": iso.VED{},
		"VES": iso.VES{},
		"VND": iso.VND{},
		"VUV": iso.VUV{},
		"WST": iso.WST{},
		"XAD": iso.XAD{},
		"XAF": iso.XAF{},
		"XAG": iso.XAG{},
		"XAU": iso.XAU{},
		"XBA": iso.XBA{},
		"XBB": iso.XBB{},
		"XBC": iso.XBC{},
		"XBD": iso.XBD{},
		"XCD": iso.XCD{},
		"XCG": iso.XCG{},
		"XDR": iso.XDR{},
		"XOF": iso.XOF{},
		"XPD": iso.XPD{},
		"XPF": iso.XPF{},
		"XPT": iso.XPT{},
		"XSU": iso.XSU{},
		"XTS": iso.XTS{},
		"XUA": iso.XUA{},
		"XXX": iso.XXX{},
		"YER": iso.YER{},
		"ZAR": iso.ZAR{},
		"ZMW": iso.ZMW{},
		"ZWG": iso.ZWG{},
	}
	if len(markers) != len(money.Currencies()) {
		t.Fatalf("%d markers for %d currencies", len(markers), len(money.Currencies()))
	}
	for code, marker := range markers {
		if marker.CurrencyCode() != code {
			t.Errorf("marker %s returns %q", code, marker.CurrencyCode())
		}
		if _, err := money.LookupCurrency(code); err != nil {
			t.Errorf("marker %s: %v", code, err)
		}
	}
}
